/// <reference types="cypress" />
import { onAccountBlocksPage } from '../support/pageObjects/AccountBlocksPageAOFI.js';
import { onAPI } from '../support/pageObjects/API.js';
import { Assert } from '../support/pageObjects/assertions.js';
import { onBuyerDataPage } from '../support/pageObjects/BuyerDataPageAOFI.js';
import { onCompanyActivitiesPageAOFI } from '../support/pageObjects/CompanyActivitiesPageAOFI.js';
import { onCompetitorsPage } from '../support/pageObjects/CompetitorsPageAOFI.js';
import { onCourtDisputePage } from '../support/pageObjects/CourtDisputesPageAOFI.js';
import { onDocumentationPage } from '../support/pageObjects/DocumentationPageAOFI.js';
import { onExportActivityPage } from '../support/pageObjects/ExportActivityPageAOFI.js';
import { onGeneralCommentPage } from '../support/pageObjects/GeneralCommentPageAOFI.js';
import { onJobsFinancedPage } from '../support/pageObjects/JobsFinancedPageAOFI.js';
import { onLegalEntitiesPage } from '../support/pageObjects/LegalEntitiesPageAOFI.js';
import { onLoanRequestForm } from '../support/pageObjects/LoanRequestFormAOFI.js';
import { onManagementStructurePage } from '../support/pageObjects/ManagementStructurePageAOFI.js';
import { onObligationsPage } from '../support/pageObjects/ObligationsPageAOFI.js';
import { onPaymentTransactionsPage } from '../support/pageObjects/PaymentTransactionsPageAOFI.js';
import { onRealEstatePage } from '../support/pageObjects/RealEstateAndEquipmentPageAOFI.js';
import { onReferenceListPage } from '../support/pageObjects/ReferenceListPageAOFI.js';
import { onRequestPageAOFI } from '../support/pageObjects/RequestPageAOFI.js';
import { onSalesPage } from '../support/pageObjects/SalesPageAOFI.js';
import { onStakeholdersPageAOFI } from '../support/pageObjects/StakeholdersPageAOFI.js';
import { onStatusChangesAOFI } from '../support/pageObjects/StatusChangesPageAOFI.js';
import { onSupplierDataPage } from '../support/pageObjects/SupplierDataPageAOFI.js';

describe('Loan request test', () => {
  beforeEach(() => {
    cy.clearLocalStorage();
    cy.goToLoginPage();
    cy.validLoginPravnoLice();
  });

  it.only('successfully completes Loan request AOFI form as Pravno Lice (without the guarantor)', () => {
    Assert.successfulPravnoLiceLogin();
    /////// Uncoment for use of existing request: //////
    onRequestPageAOFI.searchCreatedLoanRequest('Z-504');
    Assert.searchedCreditRequestVisible('Z-504');
    onRequestPageAOFI.clickEditLoanRequestButton();
    Assert.confirmNewCreditRequestURL();
    // //////// Uncoment when creating new request: //////
    // // onRequestPageAOFI.clickAddNewCreditButton();
    // // Assert.visibleNewCreditRequestToastMsg();
    // // onRequestPageAOFI.confirmNewLoanRequestCreation();
    // // Assert.confirmNewCreditRequestURL();
    // // //////////////////////////////////////////// //
    onLoanRequestForm.fillBasicDataLoanRequest();
    onLoanRequestForm.checkTheMandatoryConditionsCheckbox();
    Assert.checkTheMandatoryConditionsCheckboxChecked();
    Assert.checkFinishAndGoToNextButtonEnabled();
    onRequestPageAOFI.clickFinishAnGoToNextButton();
    Assert.confirmCompanyActivitiesPageURL();
    onCompanyActivitiesPageAOFI.deleteAllFirstMatchingActivity();
    onCompanyActivitiesPageAOFI.addNewCompanyActivity();
    Assert.checkThatNewCompanyActivityIsAdded();
    onCompanyActivitiesPageAOFI.clickFinishAndGoToNextButton();
    Assert.confirmStatusChangesPageURL();
    onStatusChangesAOFI.enterDateOfCompanyEstablishment();
    Assert.checkThatCompanyEstablishmentYearIsAdded();
    onStatusChangesAOFI.clickFinishAndGoToNextButton();
    Assert.confirmRealEstatePageURL();
    onRealEstatePage.deleteAllFirstMatchingRealEstate();
    onRealEstatePage.addNewCompanyRealEstate();
    onRealEstatePage.fillInRealEstateData();
    Assert.checkRealEstatePageDataVisible();
    onRealEstatePage.clickFinishAndGoToNextButton();
    Assert.confirmStakeHoldersPageURL();
    onStakeholdersPageAOFI.deleteAllFirstMatchingStakeholder();
    onStakeholdersPageAOFI.addNewOwnershipStructure();
    onStakeholdersPageAOFI.fillInStakeholderData();
    onStakeholdersPageAOFI.clickFinishAndGoToNextButton();
    Assert.confirmManagementStructurePageURL();
    onManagementStructurePage.deleteAllFirstMatchingManager();
    onManagementStructurePage.addManagementStructureAndWorkExp();
    onManagementStructurePage.fillInManagementStructureData();
    Assert.checkManagementStructureDataVisible();
    onManagementStructurePage.addEmployeeStructure();
    onManagementStructurePage.fillInEmployeesStructureData();
    Assert.checkNumberOfEmployeesDataVisible();
    onManagementStructurePage.clickFinishAndGoToNextButton();
    Assert.confirmReferenceListPageURL();
    onReferenceListPage.deleteAllFirstMatchingAttachment();
    onReferenceListPage.fillInReferenceData();
    Assert.checkReferenceDataEntered();
    onReferenceListPage.attachNewDocument();
    Assert.checkReferenceListDocumentAttached();
    onReferenceListPage.clickFinishAndGoToNextButton();
    Assert.confirmSalesPageURL();
    onSalesPage.deleteAllFirstMatchingSalesProduct();
    onSalesPage.addNewSalesData();
    onSalesPage.fillInSalesData();
    Assert.checkSalesDataVisible();
    onSalesPage.clickFinishAndGoToNextButton();
    Assert.confirmSupplierDataPageURL();
    onSupplierDataPage.deleteAllFirstMatchingDomesticSupplier();
    onSupplierDataPage.addDomesticSupplier();
    onSupplierDataPage.fillInDomesticSupplierData();
    Assert.checkThatNewDomesticSupplierIsAdded();
    onSupplierDataPage.clickFinishAndGoToNextButton();
    Assert.confirmBuyerDataPageURL();
    onBuyerDataPage.deleteAllFirstMatchingForeignBuyer();
    onBuyerDataPage.addForeignBuyer();
    onBuyerDataPage.fillInForeignBuyerData();
    Assert.checkThatNewForeignBuyerIsAdded();
    onBuyerDataPage.clickFinishAndGoToNextButton();
    Assert.confirmCompetitorsPageURL();
    onCompetitorsPage.clickFinishAndGoToNextButton();
    Assert.confirmExportActivityPageURL();
    onExportActivityPage.deleteAllFirstMatchingRegionalExportActivity();
    onExportActivityPage.addRegionalExportActivity();
    onExportActivityPage.fillInRegionalExportActivityData();
    Assert.checkRegionalExportActivityDataVisible();
    onExportActivityPage.addExportBusinessRelationship();
    onExportActivityPage.fillInExportBusinessRelationshipData();
    Assert.checkExportBusinessRelationshipDataVisible();
    onExportActivityPage.clickFinishAndGoToNextButton();
    Assert.confirmJobsFinancedPageURL();
    onJobsFinancedPage.deleteAllFirstMatchingJobFinancedRevenue();
    onJobsFinancedPage.addExpectedExportRevenue();
    onJobsFinancedPage.fillInExpectedExportRevenueData();
    Assert.checkExpectedExportRevenueDataVisible();
    onJobsFinancedPage.clickFinishAndGoToNextButton();
    Assert.confirmPaymentTransactionsThroughBanksPageURL();
    onPaymentTransactionsPage.deleteAllFirstMatchingForeignExchangeTransactions();
    onPaymentTransactionsPage.addForeignExchange();
    Assert.checkForeignExchangePopupVisible();
    onPaymentTransactionsPage.fillInForeignExchangeData();
    Assert.checkPaymentTransactionForeignExchangeDataVisible();
    onPaymentTransactionsPage.clickFinishAndGoToNextButton();
    Assert.confirmAccountBlocksPageURL();
    onAccountBlocksPage.clickFinishAndGoToNextButton();
    Assert.confirmObligationsPageURL();
    onObligationsPage.clickFinishAndGoToNextButton();
    Assert.confirmRelatedLegalEntitiesPageURL();
    onLegalEntitiesPage.setRadioButtonNegative();
    onLegalEntitiesPage.clickFinishAndGoToNextButton();
    Assert.confirmCourtDisputesPageURL();
    onCourtDisputePage.setRadioButtonNegative();
    onCourtDisputePage.clickFinishAndGoToNextButton();
    Assert.confirmGeneralCommentPageURL();
    onGeneralCommentPage.addComment();
    onGeneralCommentPage.leaveComment();
    onGeneralCommentPage.clickFinishAndGoToNextButton();
    // ///////////////////////////////////////////////|
    // onLoanRequestForm.goToDocumentationPage();
    // ///////////////////////////////////////////////|
    Assert.confirmDocumentationPageURL();
    onDocumentationPage.deleteAllMatchingAttachments();
    onDocumentationPage.attachRequestForApprovalOfPlacementDocument();
    Assert.verifyCreditRequestDocumentsAttached();
    onDocumentationPage.clickFinishButton();
    Assert.confirmSubmitRequestButtonIsEnabled();
    onDocumentationPage.clickSubmitRequestButton();
    Assert.requestSuccessfullySubmittedToastVisible();
  });
});
